DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE
(
  ID BIGINT AUTO_INCREMENT NOT NULL ,
  FIRST_NAME VARCHAR(255) NOT NULL ,
  LAST_NAME VARCHAR(255) NOT NULL ,
  BIRTHDAY DATE NOT NULL ,
  ADDRESS_ID BIGINT NOT NULL ,
  CONSTRAINT EMPLOYEE_PKEY PRIMARY KEY (ID),
  CONSTRAINT EMPLOYEE_FKEY FOREIGN KEY (ID) REFERENCES ADDRESS (ID)
)CHARSET = utf8;
ALTER TABLE `test`.`employee`
  DROP FOREIGN KEY `EMPLOYEE_FKEY`;
ALTER TABLE `test`.`employee`
  ADD CONSTRAINT `EMPLOYEE_FKEY`
FOREIGN KEY (`ID`)
REFERENCES `test`.`address` (`ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
# INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, BIRTHDAY, ADDRESS_ID) VALUES('ads', 'asd', '1939-05-01' , 1)
DELETE FROM EMPLOYEE WHERE ID=1 ;