# USE TEST;
DROP TABLE IF EXISTS ADDRESS;
CREATE TABLE ADDRESS
(
  ID BIGINT AUTO_INCREMENT NOT NULL ,
  COUNTRY VARCHAR(255) NOT NULL ,
  CITY VARCHAR(255) NOT NULL ,
  STREET VARCHAR(255) NOT NULL ,
  POST_CODE VARCHAR(15) NOT NULL ,
  CONSTRAINT ADDRESS_PKEY PRIMARY KEY (ID)
)charset = utf8;
# INSERT INTO ADDRESS (ID, COUNTRY, CITY, STREET, POST_CODE) VALUES(1, 'Russia', 'SPB', 'Duduna', 123);
DELETE FROM ADDRESS WHERE ID =1;