DROP TABLE IF EXISTS EMPL_PROJ;
CREATE TABLE EMPL_PROJ
(
  EMPLOYEE_ID BIGINT NOT NULL ,
  PROJECT_ID BIGINT NOT NULL ,
  CONSTRAINT EMPL_PROJ_EMPLOYEE_ID_FKEY FOREIGN KEY (EMPLOYEE_ID) REFERENCES  EMPLOYEE (ID),
  CONSTRAINT EMPL_PROJ_PROJ_ID_FKEY FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT (ID)
)charset = utf8;
ALTER TABLE `test`.`empl_proj`
  DROP FOREIGN KEY `EMPL_PROJ_EMPLOYEE_ID_FKEY`,
  DROP FOREIGN KEY `EMPL_PROJ_PROJ_ID_FKEY`;
ALTER TABLE `test`.`empl_proj`
  ADD CONSTRAINT `EMPL_PROJ_EMPLOYEE_ID_FKEY`
FOREIGN KEY (`EMPLOYEE_ID`)
REFERENCES `test`.`employee` (`ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  ADD CONSTRAINT `EMPL_PROJ_PROJ_ID_FKEY`
FOREIGN KEY (`PROJECT_ID`)
REFERENCES `test`.`project` (`ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
DELETE FROM EMPL_PROJ WHERE PROJECT_ID=1;