CREATE TABLE EMPLOYEE
(
  ID BIGINT NOT NULL ,
  FIRST_NAME VARCHAR(255) NOT NULL ,
  LAST_NAME VARCHAR(255) NOT NULL ,
  BIRTHDAY DATE NOT NULL ,
  ADDRESS_ID BIGINT NOT NULL ,
  CONSTRAINT EMPLOYEE_PKEY PRIMARY KEY (ID),
  CONSTRAINT EMPLOYEE_FKEY FOREIGN KEY (ID) REFERENCES ADDRESS (ID)
)