# USE TEST;
CREATE TABLE ADDRESS
(
  ID BIGINT NOT NULL ,
  COUNTRY VARCHAR(255) NOT NULL ,
  CITY VARCHAR(255) NOT NULL ,
  STREET VARCHAR(255) NOT NULL ,
  POST_CODE VARCHAR(15) NOT NULL ,
  CONSTRAINT ADDRESS_PKEY PRIMARY KEY (ID)
)